name: Makefile CI

on:
  push:
    tags:
      - 'v*' # Trigger on pushes to tags starting with 'v'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make build

