name: Makefile CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important! Needed to get tags

      - name: Build .deb package
        run: make build

      - name: Get current Git tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "Found tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release with .deb asset
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_tag.outputs.tag }}
          artifacts: brent-install_*.deb
          token: ${{ secrets.GITHUB_TOKEN }}
