name: Makefile CI

on:
  push:
    tags:
      - 'v*' # Trigger on pushes to tags starting with 'v'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make build
      
    - name: Create Release and Upload .deb
      uses: softprops/action-gh-release@v1
      with:
        files: brent-install_*.deb # Replace with the actual file name or pattern of your .deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
